# Generated by Django 5.2.6 on 2025-11-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app_collabsphere', '0003_add_supabase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_object_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
